sudo: required

services:
    - docker
    - git
language: python
#
python: 3.5
#env:
#  - TOXENV=py35
#  - TOXENV=py27
#  - TOXENV=py33
#  - TOXENV=py34
#
install:
    - pip install -U cookiecutter
#
script:
    - cookicutter https://github.com/microservice-registry/docker-pk
#
#deploy:
#  provider: pypi
#  distributions: sdist
#  user: audreyr
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: audreyr/python_boilerplate
#    condition: $TOXENV == py27
