sudo: required

services:
    - docker

language: python

python: 3.5

install:
    - pip install -U cookiecutter

script:
    - mkdir docker-pk && cd docker-pk
    - cookiecutter --no-input https://github.com/microservice-registry/docker-pk
    - pwd
    - ls
